steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'deploy'
      - '${_CLOUD_RUN_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '256Mi'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'APP_DEBUG=${_APP_DEBUG},DB_CONNECTION=mysql,DB_HOST=${_DB_HOST},DB_PORT=3306,DB_DATABASE=${_DB_DATABASE},DB_USERNAME=${_DB_USERNAME},DB_PASSWORD=${_DB_PASSWORD}'
    id: Deploy
    entrypoint: 'gcloud'

  - name: 'gcr.io/google-appengine/exec-wrapper'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        /buildstep/execute.sh \
        -i gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE} \
        -e DB_CONNECTION=mysql \
        -e DB_HOST=$$DB_HOST \
        -e DB_PORT=3306 \
        -e DB_DATABASE=$$DB_DATABASE \
        -e DB_USERNAME=$$DB_USERNAME \
        -e DB_PASSWORD=$$DB_PASSWORD \
        -- php /app/artisan migrate --force
    secretEnv: ['DB_PASSWORD', 'DB_DATABASE', 'DB_USERNAME', 'DB_HOST']
    waitFor:
      - Build
      - Push
      - Deploy
    id: Migrate

availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_NUMBER/secrets/db_password/versions/1
      env: 'DB_PASSWORD'
    - versionName: projects/$_PROJECT_NUMBER/secrets/db_username/versions/1
      env: 'DB_USERNAME'
    - versionName: projects/$_PROJECT_NUMBER/secrets/db_database/versions/1
      env: 'DB_DATABASE'
    - versionName: projects/$_PROJECT_NUMBER/secrets/db_host/versions/1
      env: 'DB_HOST'

timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}'
options:
  substitutionOption: 'ALLOW_LOOSE'
substitutions:
  _APP_DEBUG: 'true'
  _CLOUD_RUN_SERVICE: 'app-lokers'
  _DB_HOST: 'mysql'
  _DB_DATABASE: 'loker_db'
  _DB_USERNAME: 'root'
  _DB_PASSWORD: 'Apacoba69'
