steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/laravel-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laravel-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'laravel-app',
      '--image', 'gcr.io/$PROJECT_ID/laravel-app',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', 'drivekj-427512:us-central1:lokerdb'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud sql connect drivekj-427512:us-central1:lokerdb --user=root --quiet < /dev/null
        php artisan migrate --force
        php artisan db:seed --force

images:
  - 'gcr.io/$PROJECT_ID/laravel-app'
